'use client'

import { useState } from 'react'
import { FileText, Flag, Shield, Lock, Crown, ArrowUpRight } from 'lucide-react'
import {
  hasFeature,
  tierThatUnlocks,
  type Entitlements,
} from '@/lib/billing/entitlements'
import type { ArtifactType } from '@/lib/reports/artifact-pdfs'

/**
 * Reports tab of the Live Command Center — the three compliance artifacts,
 * REALLY generated (SSP · POA&M · C3PAO Evidence Pack).
 *
 * The old buttons were stubs that flipped their label to "✓ …pdf" while
 * producing nothing — the same fake-success anti-pattern as the dead contact
 * form (tasks/lessons.md 2026-07-12). Every button here either produces a real
 * downloaded PDF built from the operator's own local assessment data, or shows
 * a visible error. Never a fake success.
 *
 * Gating: PDF artifacts are a paid capability (Growth+ per the entitlements
 * grid). Founder accounts are always entitled — free of cost. Locked users get
 * the truthful restriction ("Available on Growth — $499/mo") and a button that
 * opens the Plan & Unlocks view, mirroring the sidebar paywall pattern.
 *
 * Privacy: the assessment lives in the browser by design, so generation runs
 * client-side too — the data never leaves the operator's machine. The heavy
 * jsPDF + 110-control modules are dynamically imported on first click.
 */

type CardState =
  | { phase: 'idle' }
  | { phase: 'generating' }
  | { phase: 'done'; filename: string }
  | { phase: 'error'; message: string }

interface ExportRow {
  /** Monotonic id — two exports of the same artifact in the same second must
   *  still be distinct React keys. */
  id: number
  filename: string
  /** First 12 hex chars of the real SHA-256 of the generated bytes. */
  sha256: string
  at: string
}

let exportSeq = 0

const ARTIFACTS: { type: ArtifactType; icon: React.ElementType; title: string; body: string }[] = [
  {
    type: 'ssp',
    icon: FileText,
    title: 'System Security Plan',
    body: 'Full 110-control inventory with per-control status, from your assessment.',
  },
  {
    type: 'poam',
    icon: Flag,
    title: 'POA&M',
    body: 'Plan of Action & Milestones for every open control — effort-estimated.',
  },
  {
    type: 'evidence',
    icon: Shield,
    title: 'C3PAO Evidence Pack',
    body: 'Per-control evidence register in the format an assessor expects.',
  },
]

async function sha256Hex(bytes: ArrayBuffer): Promise<string> {
  try {
    const digest = await crypto.subtle.digest('SHA-256', bytes)
    return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, '0')).join('')
  } catch {
    // Non-secure contexts have no crypto.subtle — the download still proceeds.
    return ''
  }
}

export interface ReportsPanelProps {
  ent: Entitlements
  /** Founder accounts generate everything free of cost, on any tier. */
  founder?: boolean
  /** Org name fallback when no local organization profile exists. */
  orgFallback?: string
  /** Public demo (no signed-in viewer) — shows sample export history. */
  sampleMode?: boolean
  /** Opens the Plan & Unlocks tab — the restriction view for locked users. */
  onGoToPlan: () => void
}

export function ReportsPanel({ ent, founder = false, orgFallback, sampleMode = false, onGoToPlan }: ReportsPanelProps) {
  const entitled = founder || hasFeature(ent, 'pdfReports')
  const unlock = tierThatUnlocks('pdfReports')
  const unlockLabel = unlock
    ? `Available on ${unlock.name}${unlock.priceMonthly !== null ? ` — $${unlock.priceMonthly}/mo` : ''}`
    : 'Available on a paid plan'

  const [states, setStates] = useState<Record<ArtifactType, CardState>>({
    ssp: { phase: 'idle' },
    poam: { phase: 'idle' },
    evidence: { phase: 'idle' },
  })
  const [exports, setExports] = useState<ExportRow[]>([])

  const setCard = (type: ArtifactType, state: CardState) =>
    setStates((s) => ({ ...s, [type]: state }))

  const generate = async (type: ArtifactType) => {
    if (states[type].phase === 'generating') return
    setCard(type, { phase: 'generating' })
    try {
      // Heavy modules load only when the operator actually generates.
      const [{ generateArtifactPdf }, { ALL_CONTROLS }, { calculateSPRS }, storage] =
        await Promise.all([
          import('@/lib/reports/artifact-pdfs'),
          import('@/lib/shieldready/controls'),
          import('@/lib/shieldready/scoring'),
          import('@/lib/shieldready/storage'),
        ])

      const responses = storage.getAssessmentResponses()
      const org = storage.getOrganization()
      const { bytes, filename } = generateArtifactPdf(type, {
        orgName: org?.name || orgFallback || 'Your Organization',
        cmmcLevel: org?.cmmcLevel ?? 2,
        generatedAt: new Date().toISOString(),
        sprs: calculateSPRS(ALL_CONTROLS, responses),
        controls: ALL_CONTROLS,
        responses,
      })

      const sha = await sha256Hex(bytes)

      const url = URL.createObjectURL(new Blob([bytes], { type: 'application/pdf' }))
      const a = document.createElement('a')
      a.href = url
      a.download = filename
      a.click()
      URL.revokeObjectURL(url)

      setExports((rows) => [
        {
          id: ++exportSeq,
          filename,
          sha256: sha ? sha.slice(0, 12) : 'n/a',
          at: new Date().toLocaleTimeString('en-US', { hour12: false }),
        },
        ...rows,
      ])
      setCard(type, { phase: 'done', filename })
    } catch {
      setCard(type, {
        phase: 'error',
        message: 'Could not generate the PDF — reload the page and try again.',
      })
    }
  }

  return (
    <>
      {founder && (
        <div className="ops">
          <Crown style={{ width: 14, height: 14, color: 'var(--brand)' }} />
          <b>Founder access</b> <span className="sep">—</span> every report below generates free of cost.
        </div>
      )}

      <div className="cards3">
        {ARTIFACTS.map(({ type, icon: Icon, title, body }) => {
          const state = states[type]
          return (
            <div className="card" key={type}>
              <div className="ic"><Icon /></div>
              <h4>{title}</h4>
              <p>{body}</p>
              {entitled ? (
                <>
                  <button
                    type="button"
                    className="btn btn-p btn-sm"
                    style={{ marginTop: 14 }}
                    disabled={state.phase === 'generating'}
                    onClick={() => generate(type)}
                  >
                    {state.phase === 'generating'
                      ? 'Generating…'
                      : state.phase === 'done'
                        ? 'Download again'
                        : 'Generate PDF'}
                  </button>
                  {state.phase === 'done' && (
                    /* role=status: success is announced to screen readers,
                       mirroring the role=alert on the error path. */
                    <p className="mono" role="status" style={{ marginTop: 8, fontSize: '.7rem', color: 'var(--ok-text)' }}>
                      ✓ Downloaded {state.filename}
                    </p>
                  )}
                  {state.phase === 'error' && (
                    <p style={{ marginTop: 8, fontSize: '.74rem', color: 'var(--bad-text)' }} role="alert">
                      {state.message}
                    </p>
                  )}
                </>
              ) : (
                <>
                  <span
                    className="mono"
                    style={{
                      display: 'inline-block', marginTop: 12, fontSize: '.66rem', fontWeight: 700,
                      color: 'var(--orange-text)', background: 'var(--orangebg)', borderRadius: 6, padding: '.2rem .5rem',
                    }}
                  >
                    <Lock style={{ width: 11, height: 11, display: 'inline', verticalAlign: -1.5, marginRight: 4 }} />
                    {unlockLabel}
                  </span>
                  <button
                    type="button"
                    className="btn btn-g btn-sm"
                    style={{ marginTop: 10 }}
                    onClick={onGoToPlan}
                  >
                    See unlock options <ArrowUpRight />
                  </button>
                </>
              )}
            </div>
          )
        })}
      </div>

      <div className="panel" style={{ marginTop: 16 }}>
        <div className="ph"><h3>Recent exports</h3><span className="mono">SHA-256 fingerprinted</span></div>
        {exports.map((row) => (
          <div className="crow" key={row.id}>
            <span>{row.filename}</span>
            <span className="mono" style={{ color: 'var(--mut2)' }}>sha256:{row.sha256}… · {row.at}</span>
          </div>
        ))}
        {exports.length === 0 && sampleMode && (
          <>
            <div className="crow"><span>SSP_AcmeDefense_2026-06.pdf</span><span className="mono" style={{ color: 'var(--mut2)' }}>sample · 2d ago</span></div>
            <div className="crow"><span>SPRS_attestation_Q2.pdf</span><span className="mono" style={{ color: 'var(--mut2)' }}>sample · 5d ago</span></div>
            <div className="crow"><span>Audit_trail_May.json</span><span className="mono" style={{ color: 'var(--mut2)' }}>sample · 12d ago</span></div>
          </>
        )}
        {exports.length === 0 && !sampleMode && (
          <div className="crow"><span style={{ color: 'var(--mut2)' }}>No exports yet — generate your first artifact above.</span></div>
        )}
      </div>
    </>
  )
}
