import { Resend } from "resend";

/**
 * Transactional auth emails for Better Auth (password reset + verification),
 * sent through Resend (already the app's email provider).
 *
 * The content builders are pure and exported for testing. Sending is a graceful
 * no-op when RESEND_API_KEY is absent (dev / demo) so auth flows never hard-fail
 * on a missing key. The `url` values are generated by Better Auth against our
 * own origin, so they are trusted; still emitted into href/text only.
 */

const FROM = "HoundShield <noreply@houndshield.com>";
const BRAND = "#5A86A8"; // --hs-steel-dark

export interface EmailContent {
  subject: string;
  html: string;
  text: string;
}

/** Minimal branded shell — no external assets (email clients strip most CSS). */
function shell(heading: string, bodyHtml: string, buttonLabel: string, url: string): string {
  return `<!doctype html><html><body style="margin:0;background:#F5F8FB;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#0F1E2E">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px">
    <tr><td align="center">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:480px;background:#fff;border:1px solid rgba(15,30,46,.10);border-radius:14px;overflow:hidden">
        <tr><td style="padding:22px 28px;border-bottom:1px solid rgba(15,30,46,.08);font-weight:700;font-size:18px">Hound<span style="color:${BRAND}">Shield</span></td></tr>
        <tr><td style="padding:28px">
          <h1 style="margin:0 0 12px;font-size:20px">${heading}</h1>
          ${bodyHtml}
          <table role="presentation" cellpadding="0" cellspacing="0" style="margin:22px 0"><tr><td style="border-radius:10px;background:${BRAND}">
            <a href="${url}" style="display:inline-block;padding:12px 22px;color:#fff;text-decoration:none;font-weight:600;font-size:14px">${buttonLabel}</a>
          </td></tr></table>
          <p style="margin:16px 0 0;font-size:12px;color:#6B8299">If the button doesn't work, paste this link:<br><span style="word-break:break-all">${url}</span></p>
        </td></tr>
        <tr><td style="padding:16px 28px;border-top:1px solid rgba(15,30,46,.08);font-size:11px;color:#6B8299">HoundShield — local-only AI compliance firewall. If you didn't request this, ignore this email.</td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;
}

export function buildPasswordResetEmail(url: string): EmailContent {
  return {
    subject: "Reset your HoundShield password",
    html: shell(
      "Reset your password",
      `<p style="margin:0;font-size:14px;line-height:1.6;color:#3D5166">We received a request to reset your HoundShield password. This link expires in 1 hour and can be used once.</p>`,
      "Reset password",
      url,
    ),
    text: `Reset your HoundShield password.\n\nOpen this link (expires in 1 hour, single use):\n${url}\n\nIf you didn't request this, ignore this email.`,
  };
}

/**
 * Sign-in code email (email 2FA). Code-style layout — a large monospace code
 * instead of a button/link, since the user types it into the login screen.
 * Keep the code out of the subject line so it never shows in lock-screen
 * previews.
 */
export function buildTwoFactorCodeEmail(code: string): EmailContent {
  const html = `<!doctype html><html><body style="margin:0;background:#F5F8FB;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#0F1E2E">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px">
    <tr><td align="center">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:480px;background:#fff;border:1px solid rgba(15,30,46,.10);border-radius:14px;overflow:hidden">
        <tr><td style="padding:22px 28px;border-bottom:1px solid rgba(15,30,46,.08);font-weight:700;font-size:18px">Hound<span style="color:${BRAND}">Shield</span></td></tr>
        <tr><td style="padding:28px">
          <h1 style="margin:0 0 12px;font-size:20px">Your sign-in code</h1>
          <p style="margin:0;font-size:14px;line-height:1.6;color:#3D5166">Enter this code to finish signing in. It expires in 5 minutes and works once.</p>
          <table role="presentation" cellpadding="0" cellspacing="0" style="margin:22px 0"><tr><td style="border-radius:10px;background:#F0F5FA;border:1px solid rgba(15,30,46,.10)">
            <span style="display:inline-block;padding:14px 26px;font-family:SFMono-Regular,Menlo,Consolas,monospace;font-size:26px;font-weight:700;letter-spacing:8px;color:#0F1E2E">${code}</span>
          </td></tr></table>
          <p style="margin:16px 0 0;font-size:12px;color:#6B8299">If you didn't try to sign in, someone may have your password — reset it now.</p>
        </td></tr>
        <tr><td style="padding:16px 28px;border-top:1px solid rgba(15,30,46,.08);font-size:11px;color:#6B8299">HoundShield — local-only AI compliance firewall. HoundShield will never ask you for this code.</td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;
  return {
    subject: "Your HoundShield sign-in code",
    html,
    text: `Your HoundShield sign-in code: ${code}\n\nEnter it to finish signing in. Expires in 5 minutes, works once.\n\nIf you didn't try to sign in, reset your password now.`,
  };
}

export function buildVerificationEmail(url: string): EmailContent {
  return {
    subject: "Verify your HoundShield email",
    html: shell(
      "Verify your email",
      `<p style="margin:0;font-size:14px;line-height:1.6;color:#3D5166">Confirm your email to finish setting up your HoundShield account.</p>`,
      "Verify email",
      url,
    ),
    text: `Verify your HoundShield email.\n\nOpen this link to confirm:\n${url}`,
  };
}

async function send(to: string, content: EmailContent): Promise<void> {
  const key = process.env.RESEND_API_KEY;
  if (!key) {
    // Never block an auth flow on a missing key — log and move on.
    console.warn("[auth-emails] RESEND_API_KEY not set — skipping send:", content.subject);
    return;
  }
  try {
    const resend = new Resend(key);
    await resend.emails.send({ from: FROM, to, subject: content.subject, html: content.html, text: content.text });
  } catch (error: unknown) {
    console.error("[auth-emails] send failed:", error instanceof Error ? error.message : error);
  }
}

export async function sendPasswordResetEmail(to: string, url: string): Promise<void> {
  await send(to, buildPasswordResetEmail(url));
}

export async function sendVerificationEmail(to: string, url: string): Promise<void> {
  await send(to, buildVerificationEmail(url));
}

export async function sendTwoFactorCodeEmail(to: string, code: string): Promise<void> {
  await send(to, buildTwoFactorCodeEmail(code));
}
